---
title: "Coding 2 - Assignment 1: HTML Process Script"
author: "Ersan Kucukoglu"
date: "November 15, 2021"
output:
  prettydoc::html_pretty:
    theme: cayman
---

```{r library, echo=F}

library(rvest)
library(data.table)
library(xml2)
library(httr)
```

---
## Creating Function

```{r setup}
imdb_link <- 'https://www.imdb.com/search/title/?title_type=feature&num_votes=1000,&genres=sci-fi&sort=user_rating,desc&ref_=adv_prv'
get_movies <- function(imdb_link) {
  t <- read_html(imdb_link)
  write_html(t, 't.html')
  name <- t %>% html_nodes(".lister-item-header a") %>% html_text() 
  rel_links<-  t %>% html_nodes(".lister-item-header a") %>% html_attr("href")
  movie_links <- paste0("https://www.imdb.com",rel_links)
  year <- t %>% html_nodes(".text-muted.unbold") %>% html_text()
  rating <- t %>% html_nodes(".ratings-imdb-rating strong") %>% html_text()
  director<- t %>%  html_nodes(".text-muted+ p a:nth-child(1)") %>%  html_text()
  runtime<-  t %>%  html_nodes(".runtime") %>%  html_text()
  votes<-  t %>%  html_nodes(".sort-num_votes-visible span:nth-child(2)") %>%  html_text()
  df <- data.frame('Movie Name' = name, 'Release Year' = year,'Movie Rating' = rating,
                   'Director' = director,'Run time' = runtime,'Votes' = votes,'Movie Links' = movie_links)
}
```

## Adding Links
```{r adding links}

links <- paste0("https://www.imdb.com/search/title/?title_type=feature&num_votes=1000,&genres=sci-fi&sort=user_rating,desc&start=",
               seq(from=1,to=101,by=50))
```

## Creating Data Frame
```{r pressure}
df_list<- lapply(links, get_movies)

movies_df<- rbindlist(df_list)
```

## Final Data Table
```{r, echo=FALSE}
dataset1 <- head(movies_df)
write.csv(movies_df,"movies.csv")
knitr::kable(dataset1)
```
